Update main.go
Running the application without these imports will throw the below error:

macbookpro@Favours-MacBook-Pro sample-golang-app % SERVICE_NAME=goGinApp INSECURE_MODE=true OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317 go run main.go
# command-line-arguments
./main.go:25:17: undefined: os
./main.go:26:17: undefined: os
./main.go:27:17: undefined: os
./main.go:31:24: undefined: context
./main.go:35:8: undefined: strings
./main.go:42:9: undefined: context
./main.go:50:9: undefined: log
./main.go:53:9: undefined: context
./main.go:60:9: undefined: log
./main.go:75:19: undefined: context
./main.go:75:19: too many errors


This step also wasn't added in the tutorial on the website so it will fail.